[pytest]
testpaths = tests
python_files = test_*.py check_*.py verify_*.py
python_functions = test_* check_* verify_*
addopts = -v -ra --tb=short

markers =
    core: Essential functionality.
    unstable_core: Essential functionality, but rests on external systems so 80% failure is okay.
    nice_to_have: Non-breaking features. Will generally either be removed or moved to core.
    experimental: Unstable or new features.

